# Generated by Django 4.0.6 on 2022-07-19 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='edited',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 13, 4, 31, 837302, tzinfo=utc), editable=False, verbose_name='posted on'),
        ),
    ]
