# Generated by Django 4.0.6 on 2022-07-19 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_edited_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 18, 13, 28, 314269, tzinfo=utc), editable=False, verbose_name='posted on'),
        ),
    ]
