# Generated by Django 4.0.6 on 2022-07-30 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_description_alter_blog_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(default=None, verbose_name='introduction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 10, 9, 14, 437964, tzinfo=utc), editable=False, verbose_name='posted on'),
        ),
    ]
