# Generated by Django 4.0.6 on 2022-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=20, verbose_name='firstname'),
        ),
    ]
