# Generated by Django 4.0.6 on 2022-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_likes_alter_blog_author_alter_blog_posted_and_more'),
        ('accounts', '0007_alter_user_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to='blogs.blog', verbose_name='saved blogs'),
        ),
    ]
