# Generated by Django 4.0.6 on 2022-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_description_alter_blog_posted'),
        ('accounts', '0008_user_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(related_name='savedblogs', to='blogs.blog', verbose_name='saved blogs'),
        ),
    ]
